import type { Metadata } from 'next';
import Link from 'next/link';
import { notFound } from 'next/navigation';
import { Calendar, CheckCircle2, ExternalLink, MapPin, ShieldCheck, Store } from 'lucide-react';
import { PublicLayout } from '@/components/layout/public-layout';
import { prisma } from '@/lib/prisma';
import { EventTrustActions } from '@/components/public/event-trust-actions';

export const dynamic = 'force-dynamic';
async function getEvent(slug: string) { try { return await prisma.publicEventListing.findFirst({ where: { slug, status: 'published', startDate: { gte: new Date(Date.now() - 14 * 86400000) } } }); } catch { return null; } }
export async function generateMetadata({ params }: { params: { slug: string } }): Promise<Metadata> { const event = await getEvent(params.slug); return event ? { title: `${event.name} — ${event.city}, ${event.state}`, description: event.description, openGraph: { title: event.name, description: event.description, images: event.imageUrl ? [event.imageUrl] : [] } } : { title: 'Event not found' }; }
export default async function CommunityEventPage({ params }: { params: { slug: string } }) {
  const event = await getEvent(params.slug); if (!event) notFound();
  const trust = event.trustStatus === 'managed' ? 'Managed on VendorFlow' : event.trustStatus === 'organizer_verified' ? 'Organizer verified' : 'Listed from a public source';
  const jsonLd = { '@context': 'https://schema.org', '@type': 'Event', name: event.name, startDate: event.startDate.toISOString(), endDate: event.endDate?.toISOString(), description: event.description, image: event.imageUrl ? [event.imageUrl] : undefined, eventStatus: 'https://schema.org/EventScheduled', eventAttendanceMode: 'https://schema.org/OfflineEventAttendanceMode', location: { '@type': 'Place', name: event.venueName, address: { '@type': 'PostalAddress', streetAddress: event.streetAddress, addressLocality: event.city, addressRegion: event.state, postalCode: event.postalCode, addressCountry: 'US' } }, organizer: { '@type': 'Organization', name: event.organizerName, url: event.sourceUrl }, offers: event.boothFeeCents != null ? { '@type': 'Offer', name: 'Vendor booth', price: event.boothFeeCents / 100, priceCurrency: 'USD', url: event.vendorApplicationUrl } : undefined };
  return <PublicLayout><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} /><article className="mx-auto max-w-4xl px-4 py-8"><Link href="/discover" className="text-sm font-medium text-orange-600">← All events</Link>
    {event.imageUrl && <img src={event.imageUrl} alt="" className="mt-5 h-72 w-full rounded-2xl object-cover" />}
    <div className="mt-6 grid gap-7 md:grid-cols-[1fr_300px]"><main><div className="inline-flex items-center gap-2 rounded-full bg-emerald-50 px-3 py-1 text-xs font-semibold text-emerald-800"><ShieldCheck className="h-3.5 w-3.5" /> {trust}</div><h1 className="mt-3 text-3xl font-bold vf-text">{event.name}</h1><p className="mt-4 leading-relaxed vf-text-muted">{event.description}</p><div className="mt-6 grid gap-3 sm:grid-cols-2"><Info icon={Calendar} title={event.startDate.toLocaleDateString('en-US', { dateStyle: 'full' })} detail={event.timeLabel ?? undefined} /><Info icon={MapPin} title={event.venueName} detail={[event.streetAddress, event.city, event.state, event.postalCode].filter(Boolean).join(', ')} /></div>
      <section className="mt-7 rounded-2xl border vf-border vf-surface p-5"><h2 className="font-semibold vf-text">Listing source</h2><p className="mt-1 text-sm vf-text-muted">Source: {event.sourceName} · Last checked {event.lastVerifiedAt?.toLocaleDateString() ?? 'pending recheck'}</p>{event.sourceUrl && <a className="mt-3 inline-flex items-center gap-1 text-sm font-semibold text-orange-600" href={event.sourceUrl} target="_blank" rel="noreferrer">View original listing <ExternalLink className="h-3.5 w-3.5" /></a>}</section>
      <EventTrustActions slug={event.slug} claimable={!event.claimedByEmail} />
    </main><aside><div className="sticky top-20 rounded-2xl border vf-border vf-surface p-5"><div className="flex items-center gap-2 font-semibold vf-text"><Store className="h-4 w-4 text-orange-600" /> Vendor opportunity</div>{event.vendorApplicationUrl ? <><p className="mt-3 text-sm vf-text-muted">{event.boothFeeCents != null ? `$${(event.boothFeeCents / 100).toFixed(0)} booth fee` : 'Contact organizer for pricing'}{event.vendorDeadline ? ` · Apply by ${event.vendorDeadline.toLocaleDateString()}` : ''}</p><a href={event.vendorApplicationUrl} target="_blank" rel="noreferrer" className="mt-4 block rounded-lg bg-orange-600 px-4 py-3 text-center font-semibold text-white">Apply with organizer</a></> : <p className="mt-3 text-sm vf-text-muted">Vendor application details have not been published yet.</p>}<p className="mt-4 flex items-start gap-2 text-xs vf-text-muted"><CheckCircle2 className="h-4 w-4 shrink-0 text-emerald-600" /> Verify deadlines and fees with the original organizer before paying.</p></div></aside></div>
  </article></PublicLayout>;
}
function Info({ icon: Icon, title, detail }: { icon: typeof Calendar; title: string; detail?: string }) { return <div className="flex gap-3 rounded-xl border vf-border vf-surface p-4"><Icon className="mt-0.5 h-5 w-5 shrink-0 text-orange-600" /><div><div className="text-sm font-semibold vf-text">{title}</div>{detail && <div className="mt-0.5 text-sm vf-text-muted">{detail}</div>}</div></div>; }
