import type {
  JurisdictionRecord,
  OpsContactRecord,
  OpsOrganizationRecord,
  OrganizationEventProfileRecord,
  OutreachActivityRecord,
} from '@/lib/ops-contacts-schema';

const now = new Date().toISOString();

export const SEED_JURISDICTIONS: JurisdictionRecord[] = [
  {
    id: 'jur-nassau',
    name: 'Nassau County',
    slug: 'nassau-county',
    county: 'nassau',
    region: 'long-island',
    state: 'NY',
  },
  {
    id: 'jur-suffolk',
    name: 'Suffolk County',
    slug: 'suffolk-county',
    county: 'suffolk',
    region: 'long-island',
    state: 'NY',
  },
  {
    id: 'jur-hempstead-village',
    name: 'Village of Hempstead',
    slug: 'village-hempstead',
    county: 'nassau',
    town: 'Hempstead',
    region: 'long-island',
    state: 'NY',
  },
  {
    id: 'jur-huntington',
    name: 'Town of Huntington',
    slug: 'town-huntington',
    county: 'suffolk',
    town: 'Huntington',
    region: 'long-island',
    state: 'NY',
  },
  {
    id: 'jur-westbury',
    name: 'Village of Westbury',
    slug: 'village-westbury',
    county: 'nassau',
    town: 'Westbury',
    region: 'long-island',
    state: 'NY',
  },
];

function contact(
  id: string,
  organizationId: string,
  data: Partial<OpsContactRecord> & Pick<OpsContactRecord, 'name'>
): OpsContactRecord {
  return {
    organizationId,
    title: data.title,
    phone: data.phone,
    email: data.email,
    linkedIn: data.linkedIn,
    department: data.department,
    preferredContactMethod: data.preferredContactMethod ?? 'email',
    purposeTags: data.purposeTags ?? ['general'],
    visibility: data.visibility ?? 'organizer-only',
    notes: data.notes ?? '',
    internalNotes: data.internalNotes,
    createdAt: now,
    updatedAt: now,
    ...data,
    id,
  };
}

function org(
  id: string,
  data: Omit<
    OpsOrganizationRecord,
    'id' | 'contacts' | 'eventProfiles' | 'outreachActivities' | 'createdAt' | 'updatedAt'
  > & {
    contacts?: OpsContactRecord[];
    eventProfiles?: OrganizationEventProfileRecord[];
    outreachActivities?: OutreachActivityRecord[];
  }
): OpsOrganizationRecord {
  return {
    ...data,
    id,
    contacts: data.contacts ?? [],
    eventProfiles: data.eventProfiles ?? [],
    outreachActivities: data.outreachActivities ?? [],
    createdAt: now,
    updatedAt: now,
  };
}

export function buildSeedOpsOrganizations(): OpsOrganizationRecord[] {
  return [
    org('org-li-hempstead-chamber', {
      type: 'chamber',
      name: 'Hempstead Chamber of Commerce',
      website: 'https://hempsteadchamber.org',
      publicPhone: '(516) 489-5000',
      publicEmail: 'events@hempsteadchamber.org',
      address: '120 Main St, Hempstead, NY 11550',
      jurisdictionId: 'jur-hempstead-village',
      jurisdiction: SEED_JURISDICTIONS.find(j => j.id === 'jur-hempstead-village'),
      jurisdictionCoverage: ['Hempstead', 'West Hempstead', 'Uniondale'],
      notes: 'Primary pilot partner. Runs summer street fair series downtown.',
      recurringEventTypes: ['street-fair', 'farmers-market'],
      vendorHeavy: true,
      fitScore: 95,
      internalOnly: false,
      outreachStatus: 'active',
      defaultVisibility: 'organizer-only',
      contacts: [
        contact('c-hcc-1', 'org-li-hempstead-chamber', {
          name: 'Maria Lopez',
          title: 'Events Director',
          phone: '(516) 489-5001',
          email: 'maria@hempsteadchamber.org',
          purposeTags: ['vendor-applications', 'event-day', 'logistics'],
          visibility: 'organizer-only',
          notes: 'Primary POC for vendor approvals and booth assignments.',
        }),
        contact('c-hcc-2', 'org-li-hempstead-chamber', {
          name: 'James Chen',
          title: 'Operations Manager',
          phone: '(516) 489-5002',
          email: 'james@hempsteadchamber.org',
          purposeTags: ['event-day', 'road-closures', 'sanitation'],
          visibility: 'approved-vendor',
        }),
      ],
      eventProfiles: [
        {
          id: 'ep-hcc-1',
          organizationId: 'org-li-hempstead-chamber',
          eventDistrict: 'Downtown Hempstead',
          eventTypes: ['street-fair', 'holiday-market'],
          seasonality: 'May–October',
          typicalVendorCount: 60,
          notes: 'Main Ave closed 6am–8pm event days.',
        },
      ],
      outreachActivities: [
        {
          id: 'oa-hcc-1',
          organizationId: 'org-li-hempstead-chamber',
          activityType: 'meeting',
          summary: 'Pilot kickoff — agreed to run 2026 summer series on VendorFlow',
          actorLabel: 'VendorFlow team',
          createdAt: now,
        },
      ],
    }),
    org('org-li-nassau-health', {
      type: 'health-department',
      name: 'Nassau County Dept. of Health — Food Service',
      website: 'https://www.nassaucountyny.gov/health',
      publicPhone: '(516) 227-9717',
      publicEmail: 'foodsafety@nassaucountyny.gov',
      address: '200 County Seat Dr, Mineola, NY 11501',
      jurisdictionId: 'jur-nassau',
      jurisdiction: SEED_JURISDICTIONS.find(j => j.id === 'jur-nassau'),
      jurisdictionCoverage: ['Nassau County'],
      notes: 'Temporary food permits required for prepared food vendors.',
      recurringEventTypes: ['street-fair', 'festival'],
      vendorHeavy: true,
      fitScore: 88,
      internalOnly: false,
      outreachStatus: 'active',
      defaultVisibility: 'organizer-only',
      contacts: [
        contact('c-nh-1', 'org-li-nassau-health', {
          name: 'Permit Desk',
          title: 'Temporary Event Food Permits',
          phone: '(516) 227-9717',
          email: 'foodsafety@nassaucountyny.gov',
          department: 'Food Protection',
          purposeTags: ['food', 'permits'],
          visibility: 'organizer-only',
          notes: 'Apply 30 days before event. CE-200 may also be required.',
        }),
      ],
    }),
    org('org-li-nassau-fire-marshal', {
      type: 'fire-marshal',
      name: 'Nassau County Fire Marshal — Public Events',
      publicPhone: '(516) 573-9900',
      publicEmail: 'firemarshal@nassaucountyny.gov',
      jurisdictionId: 'jur-nassau',
      jurisdiction: SEED_JURISDICTIONS.find(j => j.id === 'jur-nassau'),
      jurisdictionCoverage: ['Nassau County'],
      notes: 'Fire safety plan review for tents, propane, generators.',
      recurringEventTypes: ['street-fair', 'festival', 'carnival'],
      vendorHeavy: true,
      fitScore: 90,
      internalOnly: false,
      outreachStatus: 'contacted',
      defaultVisibility: 'organizer-only',
      contacts: [
        contact('c-nfm-1', 'org-li-nassau-fire-marshal', {
          name: 'Events Unit',
          title: 'Fire Safety Inspections',
          phone: '(516) 573-9900',
          email: 'firemarshal@nassaucountyny.gov',
          purposeTags: ['fire', 'permits', 'event-day'],
          visibility: 'organizer-only',
          notes: 'Submit tent layout + vendor list 14 days out.',
        }),
      ],
    }),
    org('org-li-hempstead-village-clerk', {
      type: 'village-office',
      name: 'Village of Hempstead — Clerk & Permits',
      publicPhone: '(516) 489-3400',
      publicEmail: 'clerk@villageofhempstead.org',
      address: '99 Nichols Ct, Hempstead, NY 11550',
      jurisdictionId: 'jur-hempstead-village',
      jurisdiction: SEED_JURISDICTIONS.find(j => j.id === 'jur-hempstead-village'),
      jurisdictionCoverage: ['Hempstead Village'],
      notes: 'Special event permits, road closure requests.',
      recurringEventTypes: ['street-fair'],
      vendorHeavy: false,
      fitScore: 75,
      internalOnly: false,
      outreachStatus: 'researching',
      defaultVisibility: 'organizer-only',
      contacts: [
        contact('c-hvc-1', 'org-li-hempstead-village-clerk', {
          name: 'Village Clerk Office',
          title: 'Special Events Permits',
          phone: '(516) 489-3400',
          email: 'clerk@villageofhempstead.org',
          purposeTags: ['permits', 'road-closures'],
          visibility: 'organizer-only',
        }),
      ],
    }),
    org('org-li-hempstead-dpw', {
      type: 'sanitation-dpw',
      name: 'Village of Hempstead — DPW & Sanitation',
      publicPhone: '(516) 489-3500',
      jurisdictionId: 'jur-hempstead-village',
      jurisdiction: SEED_JURISDICTIONS.find(j => j.id === 'jur-hempstead-village'),
      jurisdictionCoverage: ['Hempstead Village'],
      notes: 'Dumpster placement, post-event cleanup coordination.',
      recurringEventTypes: ['street-fair'],
      vendorHeavy: false,
      fitScore: 70,
      internalOnly: false,
      outreachStatus: 'lead',
      defaultVisibility: 'internal',
      contacts: [
        contact('c-hdpw-1', 'org-li-hempstead-dpw', {
          name: 'Sanitation Coordinator',
          title: 'Event Cleanup',
          phone: '(516) 489-3500',
          purposeTags: ['sanitation', 'event-day', 'logistics'],
          visibility: 'internal',
          internalNotes: 'Need to confirm dumpster vendor for 2026 season.',
        }),
      ],
    }),
    org('org-li-huntington-parks', {
      type: 'parks-rec',
      name: 'Town of Huntington — Parks & Recreation',
      website: 'https://www.huntingtonny.gov/parks',
      publicPhone: '(631) 351-3099',
      publicEmail: 'parks@huntingtonny.gov',
      jurisdictionId: 'jur-huntington',
      jurisdiction: SEED_JURISDICTIONS.find(j => j.id === 'jur-huntington'),
      jurisdictionCoverage: ['Huntington', 'Cold Spring Harbor', 'Northport'],
      notes: 'Heckscher Park summer concert series and craft fairs.',
      recurringEventTypes: ['festival', 'concert-series'],
      vendorHeavy: true,
      fitScore: 82,
      internalOnly: false,
      outreachStatus: 'pilot-candidate',
      defaultVisibility: 'organizer-only',
      contacts: [
        contact('c-hp-1', 'org-li-huntington-parks', {
          name: 'Recreation Programs',
          title: 'Special Events Coordinator',
          phone: '(631) 351-3099',
          email: 'parks@huntingtonny.gov',
          purposeTags: ['vendor-applications', 'venue-coordination'],
          visibility: 'organizer-only',
        }),
      ],
    }),
    org('org-li-suffolk-health', {
      type: 'health-department',
      name: 'Suffolk County Dept. of Health Services',
      publicPhone: '(631) 854-0000',
      publicEmail: 'environmentalhealth@suffolkcountyny.gov',
      jurisdictionId: 'jur-suffolk',
      jurisdiction: SEED_JURISDICTIONS.find(j => j.id === 'jur-suffolk'),
      jurisdictionCoverage: ['Suffolk County'],
      notes: 'Food vendor permits for Suffolk events.',
      recurringEventTypes: ['street-fair', 'farmers-market'],
      vendorHeavy: true,
      fitScore: 85,
      internalOnly: false,
      outreachStatus: 'researching',
      defaultVisibility: 'organizer-only',
      contacts: [
        contact('c-sh-1', 'org-li-suffolk-health', {
          name: 'Environmental Health',
          title: 'Temporary Food Establishments',
          phone: '(631) 854-0000',
          email: 'environmentalhealth@suffolkcountyny.gov',
          purposeTags: ['food', 'permits'],
          visibility: 'organizer-only',
        }),
      ],
    }),
    org('org-li-westbury-bid', {
      type: 'bid',
      name: 'Westbury BID — Downtown Partnership',
      publicPhone: '(516) 333-0100',
      publicEmail: 'info@westburybid.org',
      jurisdictionId: 'jur-westbury',
      jurisdiction: SEED_JURISDICTIONS.find(j => j.id === 'jur-westbury'),
      jurisdictionCoverage: ['Westbury', 'Carle Place'],
      notes: 'Post Avenue street fairs and holiday strolls.',
      recurringEventTypes: ['street-fair', 'holiday-market'],
      vendorHeavy: true,
      fitScore: 78,
      internalOnly: false,
      outreachStatus: 'contacted',
      defaultVisibility: 'organizer-only',
      contacts: [
        contact('c-wb-1', 'org-li-westbury-bid', {
          name: 'Downtown Events',
          title: 'Market Manager',
          email: 'events@westburybid.org',
          phone: '(516) 333-0101',
          purposeTags: ['vendor-applications', 'logistics'],
          visibility: 'organizer-only',
        }),
      ],
    }),
    org('org-li-nassau-police', {
      type: 'police-public-safety',
      name: 'Nassau County Police — Special Events Unit',
      publicPhone: '(516) 573-7000',
      jurisdictionId: 'jur-nassau',
      jurisdiction: SEED_JURISDICTIONS.find(j => j.id === 'jur-nassau'),
      jurisdictionCoverage: ['Nassau County'],
      notes: 'Traffic control, crowd management for large events.',
      recurringEventTypes: ['festival', 'carnival'],
      vendorHeavy: false,
      fitScore: 65,
      internalOnly: true,
      outreachStatus: 'lead',
      defaultVisibility: 'internal',
      contacts: [
        contact('c-np-1', 'org-li-nassau-police', {
          name: 'Special Events Desk',
          title: 'Event Security Coordination',
          phone: '(516) 573-7000',
          purposeTags: ['public-safety', 'event-day', 'road-closures'],
          visibility: 'internal',
          internalNotes: 'Requires 60-day notice for events over 5,000 attendees.',
        }),
      ],
    }),
  ];
}

export { SEED_JURISDICTIONS as seedJurisdictions };
